export DYLD_LIBRARY_PATH="/Users/pete/Temp/rsgislibdev/lib"

python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Temp/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/FieldIs_APIclip.shp"  --canopymaskdc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/FieldIs_1991_CanopyMask_1m.kea --canopycover /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/FieldIs_1991_CanopyCover.kea --extractpvcc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/FieldIs_1991_Stats.h5 --tmp /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/tmp


python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Temp/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/SAlligator_APIclip.shp"  --canopymaskdc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/SAlligator_1991_CanopyMask_1m.kea --canopycover /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/SAlligator_1991_CanopyCover.kea --extractpvcc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/SAlligator_1991_Stats.h5 --tmp /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/tmp


python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Temp/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/WAlligator_API_clip.shp"  --canopymaskdc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/WAlligator_1991_CanopyMask_1m.kea --canopycover /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/WAlligator_1991_CanopyCover.kea --extractpvcc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/WAlligator_1991_Stats.h5 --tmp /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/tmp


python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Temp/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/Wildman_APIclip.shp"  --canopymaskdc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Wildman_1991_CanopyMask_1m.kea --canopycover /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Wildman_1991_CanopyCover.kea --extractpvcc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Wildman_1991_Stats.h5 --tmp /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/tmp


python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Temp/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_2002.tif --canopymask "/Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/CASI 2002/CASI_Final.shp"  --canopymaskdc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/WAlligator_2002_CanopyMask_1m.kea --canopycover /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/WAlligator_2002_CanopyCover.kea --extractpvcc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/WAlligator_2002_Stats.h5 --tmp /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/tmp


python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Temp/AustralianMangroves/PV_Layers/PVFromCube_LeichardtRegion_2011.tif --canopymask "/Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/Leichardt River Mangroves/2011_Leichardt_River_MangroveExtent_LIDAR_LatLon.shp"  --canopymaskdc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Leichardt_2011_CanopyMask_1m.kea --canopycover /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Leichardt_2011_CanopyCover.kea --extractpvcc /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Leichardt_2011_Stats.h5 --tmp /Users/pete/Temp/AustralianMangroves/MangroveCanopyCover/tmp

