
#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/FieldIs_APIclip.shp"  --canopymaskdc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/FieldIs_1991_CanopyMask_1m.kea --canopycover /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/FieldIs_1991_CanopyCover.kea --extractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/FieldIs_1991_Stats.h5 --tmp /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp --aggimagelyrs /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_FieldIs_1991_CanopyCoverPC.kea --aggextractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_FieldIs_1991_Stats.h5 --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/SAlligator_APIclip.shp"  --canopymaskdc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/SAlligator_1991_CanopyMask_1m.kea --canopycover /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/SAlligator_1991_CanopyCover.kea --extractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/SAlligator_1991_Stats.h5 --tmp /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp --aggimagelyrs /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_SAlligator_1991_CanopyCoverPC.kea --aggextractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_SAlligator_1991_Stats.h5 --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/WAlligator_API_clip.shp"  --canopymaskdc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/WAlligator_1991_CanopyMask_1m.kea --canopycover /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/WAlligator_1991_CanopyCover.kea --extractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/WAlligator_1991_Stats.h5 --tmp /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp --aggimagelyrs /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_WAlligator_1991_CanopyCoverPC.kea --aggextractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_WAlligator_1991_Stats.h5 --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_1991.tif --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/API 1991/Wildman_APIclip.shp"  --canopymaskdc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Wildman_1991_CanopyMask_1m.kea --canopycover /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Wildman_1991_CanopyCover.kea --extractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Wildman_1991_Stats.h5 --tmp /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp --aggimagelyrs /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Wildman_1991_CanopyCoverPC.kea --aggextractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Wildman_1991_Stats.h5 --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_KakaduRegion_2002.tif --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/CASI 2002/CASI_Final.shp"  --canopymaskdc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/WAlligator_2002_CanopyMask_1m.kea --canopycover /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/WAlligator_2002_CanopyCover.kea --extractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/WAlligator_2002_Stats.h5 --tmp /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp --aggimagelyrs /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_WAlligator_2002_CanopyCoverPC.kea --aggextractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_WAlligator_2002_Stats.h5 --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_LeichardtRegion_2011.tif --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/Leichardt River Mangroves/2011_Leichardt_River_MangroveExtent_LIDAR_LatLon.shp"  --canopymaskdc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Leichardt_2011_CanopyMask_1m.kea --canopycover /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Leichardt_2011_CanopyCover.kea --extractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Leichardt_2011_Stats.h5 --tmp /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp --aggimagelyrs /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Leichardt_2011_CanopyCoverPC.kea --aggextractpvcc /Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Leichardt_2011_Stats.h5 --aggres 1000



#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_Minnamurra_2010.tif" --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/apl1dr_rnowraa_y2010/apl1dr_rnowraa_y20102011_MangCanopyMask.shp"  --canopymaskdc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Minnamurra_2010_CanopyMask_1m.kea" --canopycover "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Minnamurra_2010_CanopyCover.kea" --extractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Minnamurra_2010_Stats.h5" --tmp "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp" --aggimagelyrs "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Minnamurra_2010_CanopyCoverPC.kea" --aggextractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Minnamurra_2010_Stats.h5" --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_RBRISBA_2009.tif" --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/Brisbane_2009/apl1dr_rbrisba_2009_lidarchm_mangCanpyMsk_shp.shp"  --canopymaskdc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Brisbane_2009_CanopyMask_1m.kea" --canopycover "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Brisbane_2009_CanopyCover.kea" --extractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Brisbane_2009_Stats.h5" --tmp "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp" --aggimagelyrs "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Brisbane_2009_CanopyCoverPC.kea" --aggextractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Brisbane_2009_Stats.h5" --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_RBUNDAB_2011.tif" --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/rbundab_2011/apl1dr_rbundab_2011_lidarchm_mangCanpyMsk_shp.shp"  --canopymaskdc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Hervey_2011_CanopyMask_1m.kea" --canopycover "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Hervey_2011_CanopyCover.kea" --extractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Hervey_2011_Stats.h5" --tmp "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp" --aggimagelyrs "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Hervey_2011_CanopyCoverPC.kea" --aggextractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Hervey_2011_Stats.h5" --aggres 1000


#python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_RPORCOM_2006.tif" --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/rporcom_2006/apukdr_rporcom_2006_lidarchm_mangCanpyMsk_shp.shp"  --canopymaskdc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Aurukun_2006_CanopyMask_1m.kea" --canopycover "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Aurukun_2006_CanopyCover.kea" --extractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Aurukun_2006_Stats.h5" --tmp "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp" --aggimagelyrs "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Aurukun_2006_CanopyCoverPC.kea" --aggextractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Aurukun_2006_Stats.h5" --aggres 1000







python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_Adelade_2016.tif" --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/Adelaide_2016/1m_CHM_Adl_mangCanpyMsk_shp.shp"  --canopymaskdc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Adelade_2016_CanopyMask_1m.kea" --canopycover "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Adelade_2016_CanopyCover.kea" --extractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Adelade_2016_Stats.h5" --tmp "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp" --aggimagelyrs "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Adelade_2016_CanopyCoverPC.kea" --aggextractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Adelade_2016_Stats.h5" --aggres 1000






python /Users/pete/Development/agdc_mangrovemonitoring/CanopyCover/CreateDataCubeCanopyCover.py --dcpvf "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/PV_Layers/PVFromCube_Exmouth_2016.tif" --canopymask "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/RAWBaseMaps/Exmouth_2016/chm_spike_free_mangCanpyMsk_shp.shp"  --canopymaskdc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/MangroveExtentMaps/Exmouth_2016_CanopyMask_1m.kea" --canopycover "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/CanopyCoverEst/Exmouth_2016_CanopyCover.kea" --extractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/ExtractedCoverPVStats/Exmouth_2016_Stats.h5" --tmp "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/tmp" --aggimagelyrs "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggOutImgs/Agg_Exmouth_2016_CanopyCoverPC.kea" --aggextractpvcc "/Users/pete/Dropbox (EOED)/PeteBunting/Projects/AustralianMangroves/MangroveCanopyCover/AggExtData/Agg_Exmouth_2016_Stats.h5" --aggres 1000


